"use client";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabase";
type Row={trip_number:string;unit_cost:number|null;annual_trip_cost:number|null;calculated_rate_per_mile:number|null;equipment_type:string|null;frequency:string|null;annual_trip_count:number|null;per_trip_miles:number|null;annual_miles:number|null;per_trip_hours:number|null;effective_start:string;effective_end:string|null};
const money=(n:number|null)=>n==null?"—":Number(n).toLocaleString("en-US",{style:"currency",currency:"USD"});
const num=(n:number|null,d=1)=>n==null?"—":Number(n).toLocaleString("en-US",{maximumFractionDigits:d});
export default function ContractUspsTrips({contract}:{contract:string}){
 const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState("");
 useEffect(()=>{let live=true;(async()=>{const {data,error}=await supabase.from("usps_trip_rates").select("trip_number,unit_cost,annual_trip_cost,calculated_rate_per_mile,equipment_type,frequency,annual_trip_count,per_trip_miles,annual_miles,per_trip_hours,usps_contract_rate_versions!inner(effective_start,effective_end)").eq("contract_number",contract).order("trip_number");if(!live)return;if(error){setError("USPS trips will appear after the contract financial tables are installed.");setRows([]);return;}const flat=(data??[]).map((x:any)=>({...x,effective_start:x.usps_contract_rate_versions.effective_start,effective_end:x.usps_contract_rate_versions.effective_end}));setRows(flat);setError("");})();return()=>{live=false};},[contract]);
 return <section className="panel" style={{marginTop:24}}><div className="panel-heading"><div><p className="eyebrow">USPS schedule</p><h2>Trips</h2><span>Official USPS trip rates and schedule mileage, preserved by effective period.</span></div></div>{error?<p>{error}</p>:rows.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>Trip</th><th>Unit cost</th><th>Annual cost</th><th>Rate/mi</th><th>Miles/trip</th><th>Annual miles</th><th>Annual trips</th><th>Equipment</th><th>Frequency</th><th>Effective</th><th>Through</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.trip_number+"-"+r.effective_start+"-"+i}><td><strong>{r.trip_number}</strong></td><td>{money(r.unit_cost)}</td><td>{money(r.annual_trip_cost)}</td><td>{money(r.calculated_rate_per_mile)}</td><td>{num(r.per_trip_miles)}</td><td>{num(r.annual_miles,0)}</td><td>{num(r.annual_trip_count,0)}</td><td>{r.equipment_type??"—"}</td><td>{r.frequency??"—"}</td><td>{r.effective_start}</td><td>{r.effective_end??"Current"}</td></tr>)}</tbody></table></div>:<p>No imported USPS trips are available for this contract yet.</p>}</section>;
}