"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Trip = { trip_number:string; frequency_code:string|null; trip_miles:number|null; trip_hours:number|null; vehicle_type:string|null; effective_from:string; effective_to:string|null; change_type:string|null; source_notes:string|null; source_document_id:string|null };
type Doc = { id:string; document_name:string; document_type:string; effective_date:string|null; created_at:string };
const number=(value:number|null,decimals=1)=>value==null?"—":Number(value).toLocaleString("en-US",{maximumFractionDigits:decimals});

export default function ContractScheduleHistory({contract}:{contract:string}){
 const [allowed,setAllowed]=useState(false);const [trips,setTrips]=useState<Trip[]>([]);const [docs,setDocs]=useState<Doc[]>([]);const [error,setError]=useState("");const [loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;void(async()=>{const permission=await supabase.rpc("is_contract_financial_user");if(!active)return;if(permission.data!==true){setLoading(false);return;}setAllowed(true);const [tripResult,docResult]=await Promise.all([supabase.from("contract_trip_versions").select("trip_number,frequency_code,trip_miles,trip_hours,vehicle_type,effective_from,effective_to,change_type,source_notes,source_document_id").eq("contract_number",contract.toUpperCase()).order("trip_number"),supabase.from("contract_source_documents").select("id,document_name,document_type,effective_date,created_at").eq("contract_number",contract.toUpperCase()).order("effective_date",{ascending:false}).order("created_at",{ascending:false})]);if(!active)return;if(tripResult.error)setError(tripResult.error.message);else setTrips((tripResult.data||[]) as Trip[]);if(!docResult.error)setDocs((docResult.data||[]) as Doc[]);setLoading(false);})();return()=>{active=false};},[contract]);
 const latest=useMemo(()=>{const byTrip=new Map<string,Trip>();for(const trip of trips){const prior=byTrip.get(trip.trip_number);if(!prior||trip.effective_from>prior.effective_from)byTrip.set(trip.trip_number,trip);}return [...byTrip.values()].sort((a,b)=>Number(a.trip_number)-Number(b.trip_number));},[trips]);
 const dates=useMemo(()=>[...new Set(trips.map(t=>t.effective_from).filter(Boolean))].sort().reverse(),[trips]);
 if(!allowed&&!loading)return null;
 return <section className="panel no-print" style={{marginBottom:18}}><div className="panel-heading"><div><p className="eyebrow">USPS contract source of truth</p><h2>Current contract schedule</h2><span>Reviewed base schedules and service changes saved from USPS PDFs. Older effective-dated versions remain in history.</span></div><Link className="hub-secondary-link" href="/contracts/schedules">Upload revised schedule →</Link></div>
 {loading?<div className="hub-loading">Loading saved schedule…</div>:error?<div className="alert alert-error">{error}</div>:!trips.length?<div className="location-empty">No reviewed USPS schedule has been saved for {contract} yet. <Link href="/contracts/schedules">Upload the contract schedule →</Link></div>:<>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:10,marginBottom:14}}><div style={{padding:12,background:"#f5f8fb",borderRadius:10}}><span style={{fontSize:12,color:"#607286"}}>Current trips</span><strong style={{display:"block",fontSize:21,color:"#0f2747"}}>{latest.length}</strong></div><div style={{padding:12,background:"#f5f8fb",borderRadius:10}}><span style={{fontSize:12,color:"#607286"}}>Effective dates</span><strong style={{display:"block",fontSize:21,color:"#0f2747"}}>{dates.length}</strong></div><div style={{padding:12,background:"#f5f8fb",borderRadius:10}}><span style={{fontSize:12,color:"#607286"}}>Source documents</span><strong style={{display:"block",fontSize:21,color:"#0f2747"}}>{docs.length}</strong></div></div>
 <details open className="contract-trip-details"><summary>Current trip schedule ({latest.length})</summary><div className="table-scroll"><table className="data-table"><thead><tr><th>Trip</th><th>Frequency</th><th>Vehicle</th><th>Miles</th><th>Hours</th><th>Effective</th><th>Expires</th></tr></thead><tbody>{latest.map(t=><tr key={`${t.trip_number}-${t.effective_from}`}><td><strong>{t.trip_number}</strong></td><td>{t.frequency_code||"—"}</td><td>{t.vehicle_type||"—"}</td><td>{number(t.trip_miles)}</td><td>{number(t.trip_hours,2)}</td><td>{t.effective_from}</td><td>{t.effective_to||"Current"}</td></tr>)}</tbody></table></div></details>
 <details className="contract-trip-details" style={{marginTop:10}}><summary>Schedule history and service changes ({trips.length} saved versions)</summary><div style={{padding:"10px 0",fontSize:13,color:"#52677f"}}>{docs.length?docs.map(d=><div key={d.id} style={{padding:"6px 0",borderBottom:"1px solid #edf1f5"}}><strong>{d.document_name}</strong> · {d.document_type==="base_contract"?"Base contract":"Service change"} · effective {d.effective_date||"date not stated"}</div>):"Saved trip versions are available below."}</div><div className="table-scroll"><table className="data-table"><thead><tr><th>Trip</th><th>Change</th><th>Frequency</th><th>Miles</th><th>Hours</th><th>Effective</th><th>Expires</th><th>Notes</th></tr></thead><tbody>{[...trips].sort((a,b)=>Number(a.trip_number)-Number(b.trip_number)||b.effective_from.localeCompare(a.effective_from)).map(t=><tr key={`${t.trip_number}-${t.effective_from}-${t.source_document_id||"x"}`}><td><strong>{t.trip_number}</strong></td><td>{t.change_type||"—"}</td><td>{t.frequency_code||"—"}</td><td>{number(t.trip_miles)}</td><td>{number(t.trip_hours,2)}</td><td>{t.effective_from}</td><td>{t.effective_to||"Current"}</td><td>{t.source_notes||"—"}</td></tr>)}</tbody></table></div></details>
 </>}</section>;
}
